server:
  port: 8072

# Регистрация службы в Spring Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

# Настройки для поддержки автоматического поиска служб
# Согласно этим настройкам Spring Cloud Gateway будет автоматически обращаться к службе Eureka и определять местоположение вызываемой службы по ее идентификатору      
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
        

