spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    datasource:
      platform: postgres
      url: "jdbc:postgresql://database:5432/ostock_prod"
      username: "postgres"
      password: "{cipher}f4609209a3e75d8ac79a5e3063ce151c2cd28aa431170bb06974b9421e807b6a"
      driverClassName: org.postgresql.Driver
      testWhileIdle: true
      validationQuery: SELECT 1
    show-sql: true
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect


server:
  port: 8081

#Регистрация службы в Spring Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#Настройка шаблона размыкатель цепи
resilience4j:
  circuitbreaker:
    instances:
      organizationService:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 6
        ringBufferSizeInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60

management:
  endpoints:
    web:
      exposure:
        include: "*"
