# DataSource settings: set here your own configurations for the database
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    datasource:
      platform: postgres
    show-sql: true
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database:
        driverClassName: org.postgresql.Driver
      datasource:
        testWhileIdle: true
        validationQuery: SELECT 1
      jpa:
        hibernate:
          ddl-auto: create

server:
  port: 8081

#Регистрация службы в Spring Eureka
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

#Настройка шаблона размыкатель цепи
resilience4j:
  circuitbreaker:
    instances:
      organizationService:
        registerHealthIndicator: true
        ringBufferSizeInClosedState: 6
        ringBufferSizeInHalfOpenState: 4
        waitDurationInOpenState: 20s
        failureRateThreshold: 60

management:
  endpoints:
    web:
      exposure:
        include: "*"

#Настройка связи с KeyCloak
keycloak:
  realm: spmia-realm #Имя пространства в KeyCloak
  auth-server-url: http://localhost:8080/auth #URL конечной точки Auth сервера KeyCloak
  ssl-required: external
  resource: ostock #Идентфииктаор клиента
  credentials:
    secret: bkifrrJwmLpnbQEi2g4VRxbJZn4lUXyB #Секретный ключ клиента
  use-resource-role-mappings: true
  bearer-only: true
